"""
Django settings for minerals_investment_fund project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
env = environ.Env(
    # Set default values and casting types
    DEBUG=(bool, False)
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2j8x_s6!)xnm(5isf=-n+t-m6l6oji(13v=xj_6%r6y*)$crco'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    "unfold",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'django_bootstrap5',

    # Local apps
    'accounts',
    "visitor",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'minerals_investment_fund.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.app_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'minerals_investment_fund.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")


MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


LOGIN_URL = reverse_lazy("accounts:login")
LOGIN_REDIRECT_URL = reverse_lazy("accounts:dashboard")
LOGOUT_REDIRECT_URL = reverse_lazy("accounts:login")


UNFOLD = {
    "SITE_TITLE": "MIIF Admin Portal",
    "SITE_HEADER": "Minerals Income Investment Fund",
    "SITE_SUBHEADER": "Visitor Management System",
    "SITE_URL": "/",

    "SITE_DROPDOWN": [
        {
            "icon": "home",
            "title": _("Dashboard"),
            "link": "/",
        },
    ],
    "BORDER_RADIUS": "6px",
    "COLORS": {
        # Gold (#C9A84C) as primary — buttons, active links, highlights
        "primary": {
            "50":  "oklch(97% 0.02 85)",
            "100": "oklch(93% 0.05 85)",
            "200": "oklch(87% 0.09 85)",
            "300": "oklch(80% 0.13 85)",
            "400": "oklch(73% 0.16 85)",
            "500": "oklch(68% 0.14 85)",   # ~#C9A84C
            "600": "oklch(58% 0.13 82)",
            "700": "oklch(48% 0.11 80)",
            "800": "oklch(38% 0.09 78)",
            "900": "oklch(28% 0.07 76)",
            "950": "oklch(18% 0.05 74)",
        },
        # Ink (#1A1A1A) as base — sidebar, backgrounds, text
        "base": {
            "50":  "oklch(97% 0.001 0)",
            "100": "oklch(93% 0.002 0)",
            "200": "oklch(86% 0.003 0)",
            "300": "oklch(75% 0.004 0)",
            "400": "oklch(60% 0.004 0)",
            "500": "oklch(45% 0.003 0)",
            "600": "oklch(35% 0.003 0)",
            "700": "oklch(27% 0.002 0)",
            "800": "oklch(20% 0.002 0)",
            "900": "oklch(14% 0.001 0)",   # ~#1A1A1A
            "950": "oklch(9%  0.001 0)",
        },
    },
    "LOGIN": {
        "redirect_after": lambda request: reverse_lazy("accounts:login"),
    },


}
