# Generated by Codex on 2026-05-20

from django.db import migrations


DEPARTMENTS = [
    'Executive Office',
    'Finance & Accounts',
    'Legal & Compliance',
    'Investment & Portfolio',
    'Operations',
    'Human Resources',
    'IT & Technology',
    'Communications & PR',
    'Internal Audit',
    'Procurement',
    'Other',
]


def seed_departments(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    for name in DEPARTMENTS:
        if not Department.objects.filter(name=name).exists():
            Department.objects.create(name=name)


def unseed_departments(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    Department.objects.filter(name__in=DEPARTMENTS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_user_department'),
    ]

    operations = [
        migrations.RunPython(seed_departments, unseed_departments),
    ]
