# Generated by Codex on 2026-05-20

from django.db import migrations, models


ROLES = [
    'Can view Dashboard',
    'Register attendance/visit',
    'View Reports',
    'Admin',
]


def seed_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for name in ROLES:
        Role.objects.get_or_create(name=name)


def unseed_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(name__in=ROLES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Can view Dashboard', 'Can view Dashboard'), ('Register attendance/visit', 'Register attendance/visit'), ('View Reports', 'View Reports'), ('Admin', 'Admin')], max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role'),
        ),
        migrations.RunPython(seed_roles, unseed_roles),
    ]
