# Generated by Django 6.0.5 on 2026-05-20 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('person_to_visit', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, choices=[('Executive Office', 'Executive Office'), ('Finance & Accounts', 'Finance & Accounts'), ('Legal & Compliance', 'Legal & Compliance'), ('Investment & Portfolio', 'Investment & Portfolio'), ('Operations', 'Operations'), ('Human Resources', 'Human Resources'), ('IT & Technology', 'IT & Technology'), ('Communications & PR', 'Communications & PR'), ('Internal Audit', 'Internal Audit'), ('Procurement', 'Procurement'), ('Other', 'Other')], max_length=80)),
                ('purpose', models.CharField(choices=[('Meeting', 'Meeting'), ('Official Business', 'Official Business'), ('Delivery', 'Delivery'), ('Interview', 'Interview'), ('Contractor Work', 'Contractor Work'), ('Enquiry', 'Enquiry'), ('Other', 'Other')], max_length=60)),
                ('expected_duration', models.CharField(blank=True, choices=[('Under 30 min', 'Under 30 min'), ('30–60 min', '30–60 min'), ('1–2 hours', '1–2 hours'), ('Half day', 'Half day'), ('Full day', 'Full day')], max_length=30)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('consent_given', models.BooleanField(default=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('purge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
