# Generated by Django 6.0.5 on 2026-05-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='department',
        ),
    ]
