# Generated by Django 6.0.5 on 2026-05-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_user_department'),
        ('visitor', '0003_remove_visitor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
