# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_staff_visitor_staff_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='person_to_visit',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
